routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::prefix('front')->group(function (){


Route::post('/', [
    'uses' => 'FrontEndController@store',
    'as' => 'frontBooking.store'
]);

Route::get('/', [
    'uses' => 'FrontEndController@index',
    'as' => 'index'
]);

Route::get('/booking', [
    'uses' => 'BookingController@index',
    'as' => 'index'
]);
Route::get('/booking/step-2', [
    'uses' => 'BookingController@step2',
    'as' => 'index'
]);
Route::get('/booking/step-3', [
    'uses' => 'BookingController@step3',
    'as' => 'index'
]);
Route::get('/booking/step-4', [
    'uses' => 'BookingController@step4',
    'as' => 'index'
]);
Route::post('/booking', [
    'uses' => 'BookingController@submit',
    'as' => 'submit'
]);


//});


Route::prefix('events')->group(function () {

    Route::get('/event', [
        'uses' => 'FrontEventsController@index',
        'as' => 'event.index'
    ]);

    Route::post('/', [
        'uses' => 'FrontEventsController@store',
        'as' => 'event.store'
    ]);

});


Route::get('/resort', [
    'uses' => 'ResortController@index',
    'as' => 'resort.index'
]);


Route::get('/gallery', [
    'uses' => 'FrontEndController@viewGallery',
    'as' => 'gallery'
]);

Route::get('/resort/category', [
    'uses' => 'ResortController@roomCategory',
    'as' => 'room.category'
]);

Route::get('/resort/rooms', [
    'uses' => 'ResortController@rooms',
    'as' => 'rooms'
]);

Route::get('/blog', [
    'uses' => 'FrontBlogController@index',
    'as' => 'blog'
]);

Route::get('/contact', [
    'uses' => 'FrontEndController@contact',
    'as' => 'contact'
]);

//////Paystack route starts here
Route::post('/pay', [
    'uses' => 'PaymentController@redirectToGateway',
    'as' => 'pay'
]);
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');
/// Paystack route ends here


Auth::routes();

Route::get('/home', [
    'uses' => 'Admin\AdminController@index',
    'as' => 'admin.index'
]);
//
Route::prefix('admin')->middleware('auth')->group(function () {

    Route::get('', [
        'uses' => 'Admin\AdminController@index',
        'as' => 'admin.index'
    ]);

    ////////////Bookings Routes//////////

    Route::get('bookings/{id}/approve/', [
        'uses' => 'Admin\BookingsController@approve',
        'as' => 'booking.approve'
    ]);

    Route::get('bookings/{id}/unapprove/', [
        'uses' => 'Admin\BookingsController@unapprove',
        'as' => 'booking.unapprove'
    ]);

    Route::resource('bookings', 'Admin\BookingsController');

    Route::get('rooms/{id}/makeUnAvailable', [
        'uses' => 'Admin\RoomsController@makeUnAvailable',
        'as' => 'rooms.makeUnAvailable'
    ]);

    Route::get('rooms/{id}/makeAvailable', [
        'uses' => 'Admin\RoomsController@makeAvailable',
        'as' => 'rooms.makeAvailable'
    ]);

    Route::resource('rooms', 'Admin\RoomsController');

    Route::resource('categories', 'Admin\CategoriesController');

    Route::resource('amenities', 'Admin\AmenityController');

    Route::resource('bed_types', 'Admin\BedTypeController');

    Route::resource('settings', 'Admin\SettingsController');

    Route::resource('customers', 'Admin\CustomersController');

    ////////////Events Routes//////////

    Route::get('events/{id}/approve/', [
        'uses' => 'Admin\EventsController@approve',
        'as' => 'event.approve'
    ]);

    Route::get('events/{id}/unapprove/', [
        'uses' => 'Admin\EventsController@unapprove',
        'as' => 'event.unapprove'
    ]);

    Route::resource('events', 'Admin\EventsController');

    Route::resource('staff', 'Admin\StaffController');


    Route::resource('gallery', 'Admin\GalleryController');

    Route::resource('blog', 'Admin\BlogController');


});

app/Booking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    protected $fillable = [
        'category_id', 'room_id', 'customer_id', 'arrival', 'departure', 'email', 'phone', 'approve'
    ];

    public function room()
    {
        return $this->belongsTo(Room::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

}

app/Http/Controllers/Admin/BookingsController.php
<?php

namespace App\Http\Controllers\Admin;

use Mail;
use App\Booking;
use App\Category;
use App\Customer;
use App\Room;
use Illuminate\Auth\Middleware\Authorize;
use App\Http\Requests\CreateBookingRequest;
use App\Http\Requests\UpdateBookingRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use phpDocumentor\Reflection\Types\Null_;

class BookingsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.bookings.all_bookings')
            ->with('bookings', Booking::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $booking = DB::table('bookings')
            ->join('rooms', 'bookings.room_id', '=', 'rooms.id')
            ->join('categories', 'bookings.category_id', '=', 'categories.id')
            ->where('bookings.room_id', '=', 'rooms.id')
            ->select('bookings.room_id', 'bookings.category_id')
            ->first();
        return view('admin.bookings.create')
            ->with('booking', $booking)
            ->with('categories', Category::all())
            ->with('customers', Customer::all())
            ->with('rooms', Room::where('status', 1)->get());





    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBookingRequest $request)
    {
//        dd($request->all());

        Booking::Create([
            'category_id' => $request->category_id,
            'room_id' => $request->room_id,
            'customer_id' => $request->customer_id,
            'arrival' => $request->arrival,
            'departure' => $request->departure,
            'email' => $request->email,
            'approve' => 0
        ]);



        session()->flash('success', 'Booking successful');

        Mail::to('iwambealex25@gmail.com')->send(new \App\Mail\BookingSuccessful());


        return redirect(route('bookings.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Booking $booking)
    {
        return view('admin.bookings.create')
            ->with('booking', $booking)
            ->with('categories', Category::all())
            ->with('customers', Customer::all())
            ->with('rooms', Room::where('status', 1)->get());

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBookingRequest $request, Booking $booking)
    {
        $data = $request->only(['category_id', 'room_id', 'customer_id', 'arrival', 'departure', 'email',]);

        $booking->update($data);

        session()->flash('success', 'Booking updated successfully');

        Mail::to('00c272a1b7-b4649c@inbox.mailtrap.io')->send(new \App\Mail\BookingSuccessful());


        return redirect(route('bookings.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking)
    {
//       if ($booking->departure - $booking->arrival == 0) {

        $booking->delete();


        return redirect()->back();

    }

    public function unapprove($id)
    {

        $booking = Booking::find($id);

        // dd($booking);
        $booking->approve = false;
        $booking->room_id = NULL;
        $booking->save();

        return redirect()->back();
    }

    public function approve($id)
    {

        $booking = Booking::find($id);

        if ($booking->room_id && $booking->customer_id) {
            $booking->approve = true;
            $booking->room->status = false;
            $booking->room->save();
            $booking->save();



            return redirect()->back();

        }
        else {
            session()->flash('info', 'Please select a Customer and a room this booking');

            return redirect(route('bookings.index'));

        }



    }
}

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Event;
use Illuminate\Http\Request;

class BookingController extends Controller
{

    public function index()
    {
        $room_types = Category::getActiveRoomTypes();
//        dd($room_types);
        $elders_max = 5;
        $children_max = 5;
        return view('index')
            ->with('room_types', $room_types)
            ->with('elders_max', $elders_max)
            ->with('children_max', $children_max);
    }
    public function step2()
    {

        return view('step-2');

    }
    public function step3()
    {

        return view('step-3');

    }
    public function step4()
    {

        return view('step-4');

    }


    public function submit(Request $request){
        dd($request->all());
    }
}

resources/views/admin/bookings/all_bookings.blade.php
@extends('layouts.main')

@section('content')
    <div class="page-wrapper">
        <div class="content">
            <div class="row">

                <div class="col-sm-4 col-3">
                    <example></example>

                    <h4 class="page-title">Bookings</h4>

                @if(session()->has('info'))
                        <div class="alert alert-danger">
                            {{ session()->get('info') }}
                        </div>
                    @endif
                </div>
                <div class="col-sm-8 col-9 text-right m-b-20">
                    <a href="{{ route('bookings.create') }}" class="btn btn btn-primary btn-rounded float-right"><i class="fa fa-plus"></i> Add Booking</a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped custom-table datatable table-bordered table-condensed" id="data_table">
                            <thead>
                            <tr>
                                <th style="width:5%;">Booking ID</th>
                                <th style="width:5%;">Customer Name</th>
                                <th style="width:5%;">Room type</th>
                                <th style="width:5%;">Number</th>
                                <th style="width:5%;">Arrive</th>
                                <th style="width:5%;">Depart</th>
                                <th style="width:5%;">Email</th>
                                <th style="width:5%;">Phone</th>
                                <th style="width:5%;">Booked Time</th>
                                <th style="width:5%;">Status</th>
                                <th class="text-right">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                @foreach($bookings as $booking)
                                    <td>BK00-{{ $booking->id }}</td>

                                    @if(isset($booking->customer_id))
                                        {{--//if this booking is assigned to a customer--}}
                                        <td>{{ $booking->customer->name }}</td>
                                        <td>{{ $booking->category->type }}</td>
                                        @if(isset($booking->room->room_number))
                                            <td>{{ $booking->room->room_number }}</td>
                                        @else
                                            <td class="text-danger">Select room</td>
                                        @endif
                                        <td>{{ $booking->arrival }}</td>
                                        <td>{{ $booking->departure }}</td>
                                        <td>{{ $booking->customer->email }}</td>
                                        <td>{{ $booking->customer->phone }}</td>
                                        <td>{{ $booking->created_at->diffForHumans() }}</td>
                                    @else
                                        {{-- //if this booking has no customer assigned to it--}}
                                        <td></td>
                                        <td>{{ $booking->category->type }}</td>
                                        @if(isset($booking->room_id))
                                            <td>{{ $booking->room->room_number }}</td>
                                        @else
                                            <td class="text-danger">Select room</td>
                                        @endif
                                        <td>{{ $booking->arrival }}</td>
                                        <td>{{ $booking->departure }}</td>
                                        <td>{{ $booking->email }}</td>
                                        <td>{{ $booking->phone }}</td>
                                        <td>{{ $booking->created_at->diffForHumans() }}</td>
                                    @endif
                                        <td>
                                            @if($booking->approve)
                                                <a href="{{ route('booking.unapprove', $booking->id) }}" class="btn btn-sm btn-danger">Unapprove</a>
                                            @else
                                                <a href="{{ route('booking.approve', $booking->id) }}" class="btn btn-sm btn-primary">Approve</a>
                                            @endif
                                        </td>

                                        <td class="text-right">
                                            <div class="dropdown dropdown-action">
                                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item" href="{{ route('bookings.edit', $booking->id) }}"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                                                    <form action="{{ route('bookings.destroy', $booking->id) }}" method="post">
                                                       {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                        <button class="btn fa fa-trash-o m-r-5 mr-2" onsubmit="return confirm('Are you sure?')">Delete</button>

                                                    </form>
                                                </div>
                                            </div>
                                        </td>

                            </tr>

                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/admin/bookings/create.blade.php
@extends('layouts.main')


@section('content')
  <div class="page-wrapper">
    <div class="content">
      <div class="row">
        <div class="col-lg-8 offset-lg-2">
          <h4 class="page-title">{{ isset($room) ? 'Edit Booking' : 'Add Booking' }}</h4>
        </div>
        {{--@if($errors->any())--}}
          {{--if($count($errors) > 0 )--}}

          {{--<ul class="list-group">--}}
            {{--@foreach($errors->all() as $error)--}}

              {{--<li class="list-group-item text-danger">--}}
                {{--{{ $error }}--}}
              {{--</li>--}}
            {{--@endforeach--}}
          {{--</ul>--}}
        {{--@endif--}}

      </div>
      <div class="row">
        <div class="col-lg-8 offset-lg-2">
          <form method="post" action="{{ isset($booking) ? route('bookings.update', $booking->id) : route('bookings.store') }}">
           {{ csrf_field() }}
            @if(isset($booking))
              {{ method_field('PUT') }}

            @endif
            <div class="row">
              <div class="col-md">
                <div class="form-group">
                  <label>Customer Name</label>
                  <select name="customer_id" class="select">
                    <option value="">select customer</option>
                    @foreach($customers as $customer)
                      <option value="{{ $customer->id }}"
                              @if(isset($booking))
                              @if($booking->customer_id == $customer->id)
                              selected
                              @endif
                              @endif
                      >{{ $customer->name }}</option>

                    @endforeach
                  </select>


                  <div class="text-danger">
                    <strong>{{ $errors->first('customer_id') }}</strong>
                  </div>
                </div>
              </div>

            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>Room type</label>
                  <select name="category_id" class="select">
                    @foreach($categories as $category)
                      <option value="{{ $category->id }}"
                              @if(isset($booking))
                              @if($booking->category_id == $category->id)
                              selected
                              @endif
                              @endif
                      >{{ $category->type }}</option>

                    @endforeach
                  </select>
                  <div class="text-danger">
                    <strong>{{ $errors->first('category_id') }}</strong>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Room number</label>
                  <select name="room_id" class="select">
                    <option value="">select room</option>
                    @foreach($rooms as $room)
                      <option value="{{ $room->id }}"
                              @if(isset($booking))
                              @if($booking->room_id == $room->id)
                              selected
                              @endif
                              @endif
                      >{{ $room->room_number }}</option>

                    @endforeach
                  </select>
                  <div class="text-danger">
                    <strong>{{ $errors->first('room_id') }}</strong>
                  </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>Arrival Date </label>
                  <div class="cal-icon">
                    <input name="arrival" type="text" value="{{ isset($booking) ? $booking->arrival : '' }}" class="form-control datetimepicker ">
                 <div class="text-danger">
                   <strong>{{ $errors->first('arrival') }}</strong>
                 </div>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Departure Date </label>
                  <div class="cal-icon">
                    <input type="text" name="departure" value="{{ isset($booking) ? $booking->departure : '' }}" class="form-control datetimepicker">
                    <div class="text-danger">
                      <strong>{{ $errors->first('departure') }}</strong>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md">
                <div class="form-group">
                  <label> Email</label>
                  <input class="form-control" value="{{ isset($booking) ? $booking->email : '' }}" name="email" type="email">
                  <div class="text-danger">
                    <strong>{{ $errors->first('email') }}</strong>
                  </div>
                </div>
              </div>

            </div>
            <div class="custom-file mb-3">
              <input type="file" class="custom-file-input" name="filename">
              <label class="custom-file-label">Choose file (Photo)</label>
            </div>

            <div class="form-group">
              <label class="display-block">Booking Status</label>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="status" id="product_active" value="option1" checked>
                <label class="form-check-label" for="product_active">
                  Active
                </label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="status" id="product_inactive" value="option2">
                <label class="form-check-label" for="product_inactive">
                  Inactive
                </label>
              </div>
            </div>
            <div class="m-t-20 text-center">
              <button type="submit" class="btn btn-primary submit-btn">{{ isset($booking) ? 'Update Booking' : 'Create Booking' }}</button>
            </div>
          </form>
        </div>
      </div>
    </div>

  </div>
@endsection