routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::prefix('front')->group(function (){


Route::post('/', [
    'uses' => 'FrontEndController@store',
    'as' => 'frontBooking.store'
]);

Route::get('/', [
    'uses' => 'FrontEndController@index',
    'as' => 'index'
]);

Route::get('/booking', [
    'uses' => 'BookingController@index',
    'as' => 'index'
]);
Route::get('/booking/step-2', [
    'uses' => 'BookingController@step2',
    'as' => 'index'
]);
Route::get('/booking/step-3', [
    'uses' => 'BookingController@step3',
    'as' => 'index'
]);
Route::get('/booking/step-4', [
    'uses' => 'BookingController@step4',
    'as' => 'index'
]);
Route::post('/booking', [
    'uses' => 'BookingController@submit',
    'as' => 'submit'
]);


//});


Route::prefix('events')->group(function () {

    Route::get('/event', [
        'uses' => 'FrontEventsController@index',
        'as' => 'event.index'
    ]);

    Route::post('/', [
        'uses' => 'FrontEventsController@store',
        'as' => 'event.store'
    ]);

});


Route::get('/resort', [
    'uses' => 'ResortController@index',
    'as' => 'resort.index'
]);


Route::get('/gallery', [
    'uses' => 'FrontEndController@viewGallery',
    'as' => 'gallery'
]);

Route::get('/resort/category', [
    'uses' => 'ResortController@roomCategory',
    'as' => 'room.category'
]);

Route::get('/resort/rooms', [
    'uses' => 'ResortController@rooms',
    'as' => 'rooms'
]);

Route::get('/blog', [
    'uses' => 'FrontBlogController@index',
    'as' => 'blog'
]);

Route::get('/contact', [
    'uses' => 'FrontEndController@contact',
    'as' => 'contact'
]);

//////Paystack route starts here
Route::post('/pay', [
    'uses' => 'PaymentController@redirectToGateway',
    'as' => 'pay'
]);
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');
/// Paystack route ends here


Auth::routes();

Route::get('/home', [
    'uses' => 'Admin\AdminController@index',
    'as' => 'admin.index'
]);
//
Route::prefix('admin')->middleware('auth')->group(function () {

    Route::get('', [
        'uses' => 'Admin\AdminController@index',
        'as' => 'admin.index'
    ]);

    ////////////Bookings Routes//////////

    Route::get('bookings/{id}/approve/', [
        'uses' => 'Admin\BookingsController@approve',
        'as' => 'booking.approve'
    ]);

    Route::get('bookings/{id}/unapprove/', [
        'uses' => 'Admin\BookingsController@unapprove',
        'as' => 'booking.unapprove'
    ]);

    Route::resource('bookings', 'Admin\BookingsController');

    Route::get('rooms/{id}/makeUnAvailable', [
        'uses' => 'Admin\RoomsController@makeUnAvailable',
        'as' => 'rooms.makeUnAvailable'
    ]);

    Route::get('rooms/{id}/makeAvailable', [
        'uses' => 'Admin\RoomsController@makeAvailable',
        'as' => 'rooms.makeAvailable'
    ]);

    Route::resource('rooms', 'Admin\RoomsController');

    Route::resource('categories', 'Admin\CategoriesController');

    Route::resource('amenities', 'Admin\AmenityController');

    Route::resource('bed_types', 'Admin\BedTypeController');

    Route::resource('settings', 'Admin\SettingsController');

    Route::resource('customers', 'Admin\CustomersController');

    ////////////Events Routes//////////

    Route::get('events/{id}/approve/', [
        'uses' => 'Admin\EventsController@approve',
        'as' => 'event.approve'
    ]);

    Route::get('events/{id}/unapprove/', [
        'uses' => 'Admin\EventsController@unapprove',
        'as' => 'event.unapprove'
    ]);

    Route::resource('events', 'Admin\EventsController');

    Route::resource('staff', 'Admin\StaffController');


    Route::resource('gallery', 'Admin\GalleryController');

    Route::resource('blog', 'Admin\BlogController');


});

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    protected $fillable = [
        'firstname', 'lastname', 'username', 'email', 'address', 'password', 'role', 'staff_id', 'reg', 'phone', 'image', 'slug',
    ];

}

app/Http/Controllers/Admin/StaffController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Event;
use App\Staff;
use App\Http\Requests\UpdateStaffRequest;
use App\Http\Requests\CreateStaffRequest;
use App\Http\Controllers\Controller;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.staff.all_staff')
            ->with('staffs', Staff::all());

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.staff.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateStaffRequest $request)
    {

        if ($request->hasFile('image')) {
            Staff::Create([
                'firstname' => $request->firstname,
                'lastname' => $request->lastname,
                'username' => $request->username,
                'email' => $request->email,
                'password' => $request->password,
                'staff_id' => $request->staff_id,
                'reg' => $request->reg,
                'address' => $request->address,
                'phone' => $request->phone,
                'role' => $request->role,
                'slug' => str_slug($request->username),
                'image' => $request->image->store('public/images/staff'),


            ]);
        }

        else{
            Staff::Create([
                'firstname' => $request->firstname,
                'lastname' => $request->lastname,
                'username' => $request->username,
                'email' => $request->email,
                'password' => $request->password,
                'staff_id' => $request->staff_id,
                'address' => $request->address,
                'reg' => $request->reg,
                'phone' => $request->phone,
                'role' => $request->role,
                'slug' => str_slug($request->username),
                ]);
        }
        return redirect(route('staff.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Staff $staff)
    {
        return view('admin.staff.create')
            ->with('staff', $staff);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateStaffRequest $request, Staff $staff)
    {

        if ($request->hasFile('image'))
        {
            $staff->update([
                'firstname' => $request->firstname,
                'lastname' => $request->lastname,
                'username' => $request->username,
                'email' => $request->email,
                'password' => $request->password,
                'address' => $request->address,
                'staff_id' => $request->staff_id,
                'reg' => $request->reg,
                'phone' => $request->phone,
                'role' => $request->role,
                'slug' => str_slug($request->username),
                'image' => $request->image->store('public/images/staff'),


            ]);
        }
        else{

            $data = $request->only(['firstname', 'lastname', 'username', 'address', 'email', 'password', 'role', 'staff_id', 'reg', 'phone',  ]);
            $staff->update($data);
        }
        return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Staff $staff)
    {
        $staff->delete();
        $staff->save();

    }
}

resources/views/admin/staff/all_staff.blade.php
@extends('layouts.main')

@section('content')
    <div class="page-wrapper">
        <div class="content">
            <div class="row">
                <div class="col-sm-4 col-3">
                    <h4 class="page-title">Staff</h4>

                </div>
                <div class="col-sm-8 col-9 text-right m-b-20">
                    <a href="{{ route('staff.create') }}" class="btn btn-primary float-right btn-rounded"><i class="fa fa-plus"></i> Add Staff</a>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped custom-table datatable">
                            <thead>
                            <tr>
                                <th>Image</th>
                                <th>Staff ID</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>User Name</th>
                                <th>Email</th>
                                {{--<th>Password</th>--}}
                                <th>Join Date</th>
                                <th>Mobile</th>
                                <th style="min-width: 110px;">Role</th>
                                <th class="text-right">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($staffs as $staff)
                            <tr>
                                <td>
                                    <a href="{{ Storage::url($staff->image) }}">
                                        <img src="{{ Storage::url($staff->image) }}" width="70" height="50" alt="">
                                    </a>
                                </td>
                                <td>{{ $staff->staff_id }}</td>
                                <td>{{ $staff->firstname }}</td>
                                <td>{{ $staff->lastname }}</td>
                                <td>{{ $staff->username }}</td>
                                <td>{{ $staff->email }}</td>
                                {{--<td>{{ $staff->password }}</td>--}}
                                <td>{{ $staff->reg }}</td>
                                <td>{{ $staff->phone }}</td>
                                <td>{{ $staff->role }}</td>


                                <td class="text-right">
                                    <div class="dropdown dropdown-action">
                                        <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="{{ route('staff.edit', $staff->id) }}"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                                            <form action="{{ route('staff.destroy', $staff->id) }}" method="post">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <button class="btn fa fa-trash-o m-r-5 mr-2" onsubmit="return confirm('Are you sure?')">Delete</button>

                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div id="delete_employee" class="modal fade delete-modal" role="dialog">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-body text-center">
                            <img src="assets/img/sent.png" alt="" width="50" height="46">
                            <h3>Are you sure want to delete this Employee?</h3>
                            <div class="m-t-20"> <a href="#" class="btn btn-white" data-dismiss="modal">Close</a>
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/admin/staff/create.blade.php
@extends('layouts.main')

@section('content')
    <div class="page-wrapper">
        <div class="content">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h4 class="page-title">{{ isset($staff) ? 'Update Staff' : 'Add Staff' }}</h4>
                </div>


            </div>
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <form method="post" action="{{ isset($staff) ? route('staff.update', $staff->id) : route('staff.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        @if(isset($staff))
                            {{ method_field('PUT') }}
                        @endif
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>First Name <span class="text-danger">*</span></label>
                                    <input class="form-control" type="text" name="firstname" value="{{ isset($staff) ? $staff->firstname : '' }}">
                                <div class="text-danger">
                                    <strong>{{ $errors->first('firstname') }}</strong>
                                </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Last Name</label>
                                    <input class="form-control" type="text" name="lastname"  value="{{ isset($staff) ? $staff->lastname : '' }}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Username <span class="text-danger">*</span></label>
                                    <input class="form-control" type="text" name="username"  value="{{ isset($staff) ? $staff->username : '' }}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('username') }}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input class="form-control" type="text" name="email"  value="{{ isset($staff) ? $staff->email : '' }}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Password</label>
                                    <input class="form-control" type="text" name="password"  value="{{ isset($staff) ? $staff->password : '' }}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Address</label>
                                    <textarea name="address" class="form-control" id="" cols="3" rows="2">{{ isset($staff) ? $staff->address : ''}}</textarea>
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Staff ID <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" name="staff_id"  value="{{ isset($staff) ? $staff->staff_id : 'ST-' }}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('staff_id') }}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Joining Date <span class="text-danger">*</span></label>
                                    <div class="cal-icon">
                                        <input class="form-control datetimepicker" type="text" name="reg"  value="{{ isset($staff) ? $staff->reg : '' }}">
                                        <div class="text-danger">
                                            <strong>{{ $errors->first('reg') }}</strong>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Phone </label>
                                    <input class="form-control" type="text" name="phone"  value="{{ isset($staff) ? $staff->phone : '' }}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Role</label>
                                    <select class="select" name="role">
                                        @if(isset($staff))
                                            <option value="{{ $staff->id }}">{{ $staff->role }}</option>
                                        @else
                                        {{--<option>Admin</option>--}}
                                        <option>Manager</option>
                                        <option>Receptionist</option>
                                        <option>Accountant</option>
                                        <option>Staff</option>
                                        <option>Cleaners</option>
                                        <option>Servants</option>
                                        @endif
                                    </select>
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('role') }}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 mb-3">
                                <input type="file" class="custom-file-input" name="image">
                                <label class="custom-file-label">Choose file</label>
                                <div class="text-danger">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </div>
                            </div>
                        </div>

                        <div class="m-t-20 text-center">
                            <button type="submit" class="btn btn-primary submit-btn">{{ isset($staff) ? 'Update Staff' : 'Add Staff' }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @endsection