routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::prefix('front')->group(function (){


Route::post('/', [
    'uses' => 'FrontEndController@store',
    'as' => 'frontBooking.store'
]);

Route::get('/', [
    'uses' => 'FrontEndController@index',
    'as' => 'index'
]);

Route::get('/booking', [
    'uses' => 'BookingController@index',
    'as' => 'index'
]);
Route::get('/booking/step-2', [
    'uses' => 'BookingController@step2',
    'as' => 'index'
]);
Route::get('/booking/step-3', [
    'uses' => 'BookingController@step3',
    'as' => 'index'
]);
Route::get('/booking/step-4', [
    'uses' => 'BookingController@step4',
    'as' => 'index'
]);
Route::post('/booking', [
    'uses' => 'BookingController@submit',
    'as' => 'submit'
]);


//});


Route::prefix('events')->group(function () {

    Route::get('/event', [
        'uses' => 'FrontEventsController@index',
        'as' => 'event.index'
    ]);

    Route::post('/', [
        'uses' => 'FrontEventsController@store',
        'as' => 'event.store'
    ]);

});


Route::get('/resort', [
    'uses' => 'ResortController@index',
    'as' => 'resort.index'
]);


Route::get('/gallery', [
    'uses' => 'FrontEndController@viewGallery',
    'as' => 'gallery'
]);

Route::get('/resort/category', [
    'uses' => 'ResortController@roomCategory',
    'as' => 'room.category'
]);

Route::get('/resort/rooms', [
    'uses' => 'ResortController@rooms',
    'as' => 'rooms'
]);

Route::get('/blog', [
    'uses' => 'FrontBlogController@index',
    'as' => 'blog'
]);

Route::get('/contact', [
    'uses' => 'FrontEndController@contact',
    'as' => 'contact'
]);

//////Paystack route starts here
Route::post('/pay', [
    'uses' => 'PaymentController@redirectToGateway',
    'as' => 'pay'
]);
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');
/// Paystack route ends here


Auth::routes();

Route::get('/home', [
    'uses' => 'Admin\AdminController@index',
    'as' => 'admin.index'
]);
//
Route::prefix('admin')->middleware('auth')->group(function () {

    Route::get('', [
        'uses' => 'Admin\AdminController@index',
        'as' => 'admin.index'
    ]);

    ////////////Bookings Routes//////////

    Route::get('bookings/{id}/approve/', [
        'uses' => 'Admin\BookingsController@approve',
        'as' => 'booking.approve'
    ]);

    Route::get('bookings/{id}/unapprove/', [
        'uses' => 'Admin\BookingsController@unapprove',
        'as' => 'booking.unapprove'
    ]);

    Route::resource('bookings', 'Admin\BookingsController');

    Route::get('rooms/{id}/makeUnAvailable', [
        'uses' => 'Admin\RoomsController@makeUnAvailable',
        'as' => 'rooms.makeUnAvailable'
    ]);

    Route::get('rooms/{id}/makeAvailable', [
        'uses' => 'Admin\RoomsController@makeAvailable',
        'as' => 'rooms.makeAvailable'
    ]);

    Route::resource('rooms', 'Admin\RoomsController');

    Route::resource('categories', 'Admin\CategoriesController');

    Route::resource('amenities', 'Admin\AmenityController');

    Route::resource('bed_types', 'Admin\BedTypeController');

    Route::resource('settings', 'Admin\SettingsController');

    Route::resource('customers', 'Admin\CustomersController');

    ////////////Events Routes//////////

    Route::get('events/{id}/approve/', [
        'uses' => 'Admin\EventsController@approve',
        'as' => 'event.approve'
    ]);

    Route::get('events/{id}/unapprove/', [
        'uses' => 'Admin\EventsController@unapprove',
        'as' => 'event.unapprove'
    ]);

    Route::resource('events', 'Admin\EventsController');

    Route::resource('staff', 'Admin\StaffController');


    Route::resource('gallery', 'Admin\GalleryController');

    Route::resource('blog', 'Admin\BlogController');


});

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $fillable = [
        'name', 'email', 'phone', 'gender', 'country', 'state', 'address', 'image', 'slug',
    ];

    public function bookings()
    {
        return $this->hasMany(App\Booking);
    }

    public function events()
    {
        return $this->hasMany(App\Event);
    }
}

app/Http/Controllers/Admin/CustomersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Customer;
use App\Booking;
use App\Http\Requests\CreateCustomerRequest;
use App\Http\Requests\UpdateCustomerRequest;
use Illuminate\Support\Facades\DB;

use App\Http\Controllers\Controller;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('admin.customers.all_customers')
            ->with('customers', Customer::all())
            ->with('bookings', Booking::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.customers.create');
//            ->with('bookings', Booking::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCustomerRequest $request)
    {

//       dd($request->all());
        if($request->hasFile('image')) {





            Customer::Create([
                'name' => $request->name,
                'email' => $request->email,
                'phone' => $request->phone,
                'gender' => $request->gender,
                'country' => $request->country,
                'state' => $request->state,
                'address' => $request->address,
                'slug' => str_slug($request->name),
                'image'=> $request->image->store('public/images/customers'),
            ]);

        }
        else
        {
            Customer::Create([
                'name' => $request->name,
                'email' => $request->email,
                'phone' => $request->phone,
                'gender' => $request->gender,
                'country' => $request->country,
                'state' => $request->state,
                'address' => $request->address,
                'slug' => str_slug($request->name),
            ]);
        }
        return redirect()->back();


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        return view('admin.customers.create')
            ->with('customer', $customer);
//            ->with('bookings', Booking::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCustomerRequest $request, Customer $customer)
    {

        if( $request->hasFile('image')) {

          $customer->update([
                'name' => $request->name,
                'email' => $request->email,
                'phone' => $request->phone,
                'gender' => $request->gender,
                'country' => $request->country,
                'state' => $request->state,
                'address' => $request->address,
                'slug' => str_slug($request->name),
                'image'=> $request->image->store('public/images/customers'),
            ]);

        }
        else
        {
            $data = $request->only(['name', 'email', 'phone', 'gender', 'country', 'state', 'address']);

            $customer->update($data);

        }

        return redirect(route('customers.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        $customer->delete();

        $customer->save();

        return redirect(route('customers.index'));
    }
}

resources/views/admin/customers/all_customers.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-wrapper">
        <div class="content">
            <div class="row">
                <div class="col-sm-4 col-3">
                    <h4 class="page-title">Customers</h4>
                </div>
                <div class="col-sm-8 col-9 text-right m-b-20">
                    <a href="{{ route('customers.create') }}" class="btn btn btn-primary btn-rounded float-right"><i class="fa fa-plus"></i> Add Customer</a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped custom-table datatable">
                            <thead>
                            <tr>
                                <th style="width:20%;">Photo</th>
                                <th style="width:20%;">Name</th>
                                <th style="width:20%;">Gender</th>
                                <th>Country</th>
                                <th>State</th>
                                <th>Address</th>
                                <th style="width:20%;">Email</th>
                                <th>phone</th>
                                <th>Status</th>
                                <th class="text-right">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($customers as $customer)
                                <tr>
                                    <td>
                                        <img src="{{ Storage::url($customer->image) }}" width="100" height="100" alt="">
                                    </td>
                                    <td>{{ $customer->name }}</td>
                                    @if($customer->gender == 1)
                                        <td>Male</td>
                                    @else
                                        <td>Female</td>
                                    @endif
                                    <td>{{ $customer->country }}</td>
                                    <td>{{ $customer->state }}</td>
                                    <td>{{ $customer->address }}</td>
                                    <td>{{ $customer->email }}</td>
                                    <td>{{ $customer->phone }}</td>
                                    <td></td>
                                    <td class="text-right">
                                        <div class="dropdown dropdown-action">
                                            <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item" href="{{ route('customers.edit', $customer->id) }}"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                                                <form action="{{ route('customers.destroy', $customer->id) }}" method="post">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                        <button class="btn fa fa-trash-o m-r-5 mr-2" onsubmit="return confirm('Are you sure?')">Delete</button>

                                                    </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/customers/create.blade.php
@extends('layouts.main')


@section('content')
    <div class="page-wrapper">
        <div class="content">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h4 class="page-title">Add Customer</h4>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <form method="post" action="{{ isset($customer) ? route('customers.update', $customer->id) : route('customers.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        @if(isset($customer))
                            {{ method_field('PUT') }}
                        @endif

                        <div class="row">
                            <div class="col-md">
                                <div class="form-group">

                                    <label>Name</label>
                                    <input class="form-control" type="text" name="name" value="{{ isset($customer) ? $customer->name : ''}}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input class="form-control" {{ $errors->has('email') ? 'is-invalid' : '' }} type="text" name="email" value="{{ isset($customer) ? $customer->email : ''}}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>phone</label>
                                    <input class="form-control" type="text" name="phone" value="{{ isset($customer) ? $customer->phone : ''}}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Gender</label>
                                    <select class="select" name="gender">
                                        @if(isset($customer))
                                        @if($customer->gender == 1)
                                            <option value="1">Male</option>
                                            <option value="0">Female</option>
                                        @elseif($customer->gender == 0)
                                            <option value="0">Female</option>
                                            <option value="1">Male</option>

                                        @endif
                                        @endif
                                            <option value="1">Male</option>
                                            <option value="0">Female</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Country</label>
                                    <input type="text" class="form-control" name="country" value="{{ isset($customer) ? $customer->country : '' }}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('country') }}</strong>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>State</label>
                                    <input type="text" class="form-control" name="state" value="{{ isset($customer) ? $customer->state : '' }}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('state') }}</strong>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Address</label>
                                    <input type="text" class="form-control" name="address" value="{{ isset($customer) ? $customer->address : '' }}">
                                    <div class="text-danger">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="custom-file mb-3">
                                <input type="file" class="custom-file-input" name="image">
                                <label class="custom-file-label">Choose file (Photo)*OPTIONAL</label>
                            </div>

                            <div class="m-t-20 text-center">
                                <button class="btn btn-primary submit-btn">{{ isset($booking) ? 'Update Customer' : 'Create Customer' }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection