routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::prefix('front')->group(function (){


Route::post('/', [
    'uses' => 'FrontEndController@store',
    'as' => 'frontBooking.store'
]);

Route::get('/', [
    'uses' => 'FrontEndController@index',
    'as' => 'index'
]);

Route::get('/booking', [
    'uses' => 'BookingController@index',
    'as' => 'index'
]);
Route::get('/booking/step-2', [
    'uses' => 'BookingController@step2',
    'as' => 'index'
]);
Route::get('/booking/step-3', [
    'uses' => 'BookingController@step3',
    'as' => 'index'
]);
Route::get('/booking/step-4', [
    'uses' => 'BookingController@step4',
    'as' => 'index'
]);
Route::post('/booking', [
    'uses' => 'BookingController@submit',
    'as' => 'submit'
]);


//});


Route::prefix('events')->group(function () {

    Route::get('/event', [
        'uses' => 'FrontEventsController@index',
        'as' => 'event.index'
    ]);

    Route::post('/', [
        'uses' => 'FrontEventsController@store',
        'as' => 'event.store'
    ]);

});


Route::get('/resort', [
    'uses' => 'ResortController@index',
    'as' => 'resort.index'
]);


Route::get('/gallery', [
    'uses' => 'FrontEndController@viewGallery',
    'as' => 'gallery'
]);

Route::get('/resort/category', [
    'uses' => 'ResortController@roomCategory',
    'as' => 'room.category'
]);

Route::get('/resort/rooms', [
    'uses' => 'ResortController@rooms',
    'as' => 'rooms'
]);

Route::get('/blog', [
    'uses' => 'FrontBlogController@index',
    'as' => 'blog'
]);

Route::get('/contact', [
    'uses' => 'FrontEndController@contact',
    'as' => 'contact'
]);

//////Paystack route starts here
Route::post('/pay', [
    'uses' => 'PaymentController@redirectToGateway',
    'as' => 'pay'
]);
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');
/// Paystack route ends here


Auth::routes();

Route::get('/home', [
    'uses' => 'Admin\AdminController@index',
    'as' => 'admin.index'
]);
//
Route::prefix('admin')->middleware('auth')->group(function () {

    Route::get('', [
        'uses' => 'Admin\AdminController@index',
        'as' => 'admin.index'
    ]);

    ////////////Bookings Routes//////////

    Route::get('bookings/{id}/approve/', [
        'uses' => 'Admin\BookingsController@approve',
        'as' => 'booking.approve'
    ]);

    Route::get('bookings/{id}/unapprove/', [
        'uses' => 'Admin\BookingsController@unapprove',
        'as' => 'booking.unapprove'
    ]);

    Route::resource('bookings', 'Admin\BookingsController');

    Route::get('rooms/{id}/makeUnAvailable', [
        'uses' => 'Admin\RoomsController@makeUnAvailable',
        'as' => 'rooms.makeUnAvailable'
    ]);

    Route::get('rooms/{id}/makeAvailable', [
        'uses' => 'Admin\RoomsController@makeAvailable',
        'as' => 'rooms.makeAvailable'
    ]);

    Route::resource('rooms', 'Admin\RoomsController');

    Route::resource('categories', 'Admin\CategoriesController');

    Route::resource('amenities', 'Admin\AmenityController');

    Route::resource('bed_types', 'Admin\BedTypeController');

    Route::resource('settings', 'Admin\SettingsController');

    Route::resource('customers', 'Admin\CustomersController');

    ////////////Events Routes//////////

    Route::get('events/{id}/approve/', [
        'uses' => 'Admin\EventsController@approve',
        'as' => 'event.approve'
    ]);

    Route::get('events/{id}/unapprove/', [
        'uses' => 'Admin\EventsController@unapprove',
        'as' => 'event.unapprove'
    ]);

    Route::resource('events', 'Admin\EventsController');

    Route::resource('staff', 'Admin\StaffController');


    Route::resource('gallery', 'Admin\GalleryController');

    Route::resource('blog', 'Admin\BlogController');


});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
      'type', 'price','breakfirst_price','lunch_price','dinner_price','additional_price','status'
    ];
    public function room()
    {
        return $this->belongsTo(App\Room);
    }

    public static function getActiveRoomTypes(){
        return Category::where('status',1)->get();
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;

use App\Http\Requests\CreateCategoriesRequest;
use App\Http\Requests\UpdateCategoriesRequest;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.categories.all_categories')
            ->with('categories', Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create')
            ->with('categories', []);


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoriesRequest $request)
    {
        Category::Create([
            'type' => $request->type,
            'price' => $request->price,
            'breakfirst_price'=>$request->breakfirst_price,
            'lunch_price'=>$request->lunch_price,
            'dinner_price'=>$request->dinner_price,
            'additional_price'=>$request->additional_price,
            'status'=>$request->status
        ]);

        session()->flash('success', 'Room category created successfully');

        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit( Category $category)
    {
        return view('admin.categories.create')
            ->with('category',$category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoriesRequest $request, Category $category)
    {
        $category->update($request->except(['_token','_method']));

        session()->flash('success', 'Room category created successfully');

        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/categories/all_categories.blade.php
@extends('layouts.main')

@section('content')
    <div class="page-wrapper">
        <div class="content container-fluid">
            <div class="row">
                <div class="col-sm-8 col-4">
                    <h4 class="page-title">Pricing</h4>
                </div>
                <div class="col-sm-4 col-8 text-right m-b-30">
                    <a href="{{ route('categories.create') }}" class="btn btn-primary btn-rounded pull-right"><i
                                class="fa fa-plus"></i> Add Pricing</a>
                </div>
            </div>
            <div class="row text-center">

                @foreach($categories as $category)

                    <div class="col-sm-3 col-md-3 col-lg-3 col-xl-4">
                        <div class="pricing-box">
                            <h3 class="pricing-title">{{ $category->type }}</h3>
                            <p></p>
                            <ul class="list-group">
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    Bed Price
                                    <span class="badge-pill">
                                        <b>
                                            <sup>$</sup>{{ $category->price }}
                                        </b>
                                    </span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    Breakfirst Price
                                    <span class="badge-pill">
                                        <b>
                                            <sup>$</sup>{{ $category->breakfirst_price }}
                                        </b>
                                    </span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    Lunch Price
                                    <span class="badge-pill">
                                        <b>
                                            <sup>$</sup>{{ $category->lunch_price }}
                                        </b>
                                    </span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    Dinner Price
                                    <span class="badge-pill">
                                        <b>
                                            <sup>$</sup>{{ $category->dinner_price }}
                                        </b>
                                    </span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    Additional Price
                                    <span class="badge-pill">
                                        <b>
                                            <sup>$</sup>{{ $category->additional_price }}
                                        </b>
                                    </span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    Status
                                    <span class="badge-pill">
                                        <b>
                                            @if($category->status)
                                                <span class="badge badge-success badge-pill">Active</span>
                                            @else
                                                <span class="badge badge-danger badge-pill">Deactive</span>
                                            @endif
                                        </b>
                                    </span>
                                </li>

                            </ul>
                            <a href="{{ route('categories.edit', $category->id) }}"
                               class="btn btn-primary btn-sm btn-block w-md">Edit</a>
                        </div>
                    </div>
                @endforeach

                <div class="col-sm-6 col-md-4 col-lg-8 col-xl-3">
                    <div class="pricing-box add-pricing">
                        <div class="display-table">
                            <div class="table-cell">
                                <a href="{{ route('categories.create') }}" class="btn add-price-btn btn-rounded"><i
                                            class="fa fa-plus" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/categories/create.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-wrapper">
        <div class="content">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <h4 class="page-title">Add Pricing</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <form method="post"
                          action="{{ isset($category) ? route('categories.update',['category'=>$category->id]) : route('categories.store') }}">
                        {{ csrf_field() }}
                        @if( isset($category))
                            {{ method_field('PUT') }}
                        @endif
                        <div class="form-group">
                            <label>Pricing Name *</label>
                            <input name="type" value="{{ isset($category) ? $category->type : '' }}"
                                   class="form-control" type="text" placeholder="Single" required>
                        </div>
                        <div class="form-group">
                            <label>Bed only price * </label>
                            <input name="price" value="{{ isset($category) ? $category->price : 0 }}"
                                   class="form-control" type="text" required>
                        </div>
                        <div class="form-group">
                            <label>Breakfirst Price (Per Person)</label>
                            <input name="breakfirst_price"
                                   value="{{ isset($category) ? $category->breakfirst_price : 0 }}" class="form-control"
                                   type="text">
                        </div>
                        <div class="form-group">
                            <label>Lunch Price (Per Person)</label>
                            <input name="lunch_price" value="{{ isset($category) ? $category->lunch_price : 0 }}"
                                   class="form-control" type="text">
                        </div>
                        <div class="form-group">
                            <label>Dinner Price (Per Person)</label>
                            <input name="dinner_price" value="{{ isset($category) ? $category->dinner_price : 0 }}"
                                   class="form-control" type="text">
                        </div>
                        <div class="form-group">
                            <label>Additional Charges</label>
                            <input name="additional_price"
                                   value="{{ isset($category) ? $category->additional_price : 0 }}" class="form-control"
                                   type="text">
                        </div>
                        {{--<div class="form-group">--}}
                        {{--<label>Pricing Description</label>--}}
                        {{--<textarea cols="30" rows="6" class="form-control"></textarea>--}}
                        {{--</div>--}}
                        <div class="form-group">
                            <label class="display-block">Pricing Status</label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="status" id="pricing_active" value="1"
                                       {{ isset($category) ?  $category->status == 1 ? 'checked' : '' : 'checked' }}>
                                <label class="form-check-label" for="pricing_active">
                                    Active
                                </label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="status" id="pricing_inactive"
                                       value="0" {{ isset($category) ?  $category->status == 0 ? 'checked' : '' : '' }}>
                                <label class="form-check-label" for="pricing_inactive">
                                    Inactive
                                </label>
                            </div>
                        </div>
                        <div class="m-t-20 text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Publish Pricing</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection